import type { Metadata } from "next";
import "./globals.css";
import { Inter } from "next/font/google";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });


export const metadata: Metadata = {
  title: "CRUD OPERATION",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}:{
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <div className="max-w-3xl mx-auto text-slate-800">
        <header className="p-6 border-b flex  item- center justify-between bg-blue-500 rounded-bg-lh round-br-lg">
<Link className="text-2xl font-bold text-white" href={"/"}> Tech Interprations</Link>
<Link className="bg-slate-100 grid place-items-center py-2 px-4 rounded-full font-bold shadow-md"  href={"/create"}> Add New</Link>
        </header>
        
          <main>  {children} </main>

        </div>
      </body>
    </html>
  );
}
